### ISSUE TITLE
Multiple Issues found

### ISSUE THREAD

**Issue by sriramoffcl** [adrianchifor/pyslowloris#1]
./slowloris.py: line 3: **headers: command not found**
./slowloris.py: line 4: **User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36,: No such file or directory**
./slowloris.py: line 5: **Accept-language: en-US,en: command not found**
./slowloris.py: line 6: ]: **command not found**
./slowloris.py: line 8: **sockets: command not found**
./slowloris.py: line 10: **syntax error near unexpected token `('**
./slowloris.py: line 10: **`def setupSocket(ip):'**

**Comment by adrianchifor** [comment]
Have you read the `README.md` ? Execute as python script `python slowloris.py example.com`, not as a bash script.

**Comment by adrianchifor** [comment]
Just added the shebang to the script so it will run with python nevertheless.
